Bergwacht-System/BergwachtSystem/BergwachtSystem/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView

admin.autodiscover()

urlpatterns = [
                  url(r'^login/$', auth_views.login, name='login'),
                  url(r'^logout/$', auth_views.logout, name='logout'),
                  url(r'^admin/', include(admin.site.urls)),
                  url(r'^start/$', TemplateView.as_view(template_name='start.html'), name='start'),
                  url(r'^mitglieder/', include('member_administration.urls')),
                  url(r'^dienstplan/', include('duty_scheduler.urls')),
                  url(r'^ausbildung/', include('trainings.urls')),
                  url(r'^', include('cms.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Bergwacht-System/BergwachtSystem/duty_scheduler/urls.py
from django.conf.urls import url

from . import views

app_name = 'duty_scheduler'

urlpatterns = [
    url(r'^$', views.duty_list, name='duty_list'),
    url(r'^all/$', views.duty_list_all, name='duty_list_all'),
    url(r'^calendar/$', views.duty_calendar, name='duty_calendar'),
    url(r'^(?P<duty_number>[0-9]+)/$', views.duty_detail, name='duty_detail'),
    url(r'^anmeldung/(?P<duty_number>[0-9]+)/$', views.duty_signin, name='duty_signin'),
    url(r'^abmeldung/(?P<duty_number>[0-9]+)/$', views.duty_signout, name='duty_signout'),
]

Bergwacht-System/BergwachtSystem/member_administration/urls.py
from django.conf.urls import url

from . import views

app_name = 'member_administration'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<username>[a-z]+)/$', views.member_detail, name='member_detail'),
]

Bergwacht-System/BergwachtSystem/trainings/urls.py
from __future__ import unicode_literals
from django.conf.urls import url

from . import views

app_name = 'trainings'

urlpatterns = [
    url(r'^$', views.training_overview, name='training_overview'),
    url(r'^liste/$', views.training_list, name='training_list'),
    url(r'^termine/$', views.training_dates, name='training_dates'),
    url(r'^zeitmeldung/(?P<training_event_id>[0-9]+)/$', views.register_time_for_training,
        name='register_time_for_training'),
    url(r'^zeitabmeldung/(?P<training_event_id>[0-9]+)/$', views.deregister_time_for_training,
        name='deregister_time_for_training'),
    url(r'^zeitabmeldung/(?P<training_event_id>[0-9]+)/(?P<username>[a-z]+)/$', views.deregister_user_time_for_training,
        name='deregister_user_time_for_training'),
    url(r'^freischalten/(?P<training_event_id>[0-9]+)/$', views.permit_for_training,
        name='permit_for_training'),
    url(r'^anmeldung/(?P<training_event_id>[0-9]+)/(?P<username>[a-z]+)/$', views.register_for_training,
        name='register_for_training'),
    url(r'^abmeldung/(?P<training_event_id>[0-9]+)/(?P<username>[a-z]+)/$', views.deregister_for_training,
        name='deregister_for_training'),
    url(r'^teilnahmeeintragen/(?P<training_event_id>[0-9]+)/$', views.accept_member_trainings,
        name='accept_member_trainings'),
    url(r'^teilnahmeeintragen/(?P<training_event_id>[0-9]+)/(?P<username>[a-z]+)/$', views.register_member_training,
        name='register_member_training'),
]

Bergwacht-System/BergwachtSystem/duty_scheduler/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from member_administration.models import Member
from django.utils import timezone

class Dutyarea(models.Model):
    name = models.CharField(primary_key=True, max_length=40, verbose_name='Name')
    link = models.CharField(max_length=100, verbose_name='Link', null=True, blank=True)

    class Meta:
        verbose_name_plural = 'Dienstgebiete'
        verbose_name = 'Dienstgebiet'

    def __unicode__(self):
        return self.name


class Dutycategory(models.Model):
    name = models.CharField(primary_key=True, max_length=40, verbose_name='Name')

    class Meta:
        verbose_name_plural = 'Dienstkategorien'
        verbose_name = 'Dienstkategorie'

    def __unicode__(self):
        return self.name


class Dutyrole(models.Model):
    name = models.CharField(primary_key=True, max_length=40, verbose_name='Name')
    shortname = models.CharField(max_length=10, verbose_name='Kürzel')

    class Meta:
        verbose_name_plural = 'Dienstrollen'
        verbose_name = 'Dienstrolle'

    def __unicode__(self):
        return self.name


# Defines a "Dienst" of the Bergwacht
class Duty(models.Model):
    duty_number = models.AutoField(primary_key=True, verbose_name='Dienstnummer')
    duty_area = models.ForeignKey(Dutyarea, on_delete=models.CASCADE, verbose_name='Dienstgebiet')
    duty_start = models.DateTimeField(verbose_name='Dienstbeginn')
    duty_end = models.DateTimeField(verbose_name='Dienstende')
    minaek = models.IntegerField(verbose_name='Geforderte AEK', blank=True, null=True)
    category = models.ForeignKey(Dutycategory, on_delete=models.CASCADE, null=True)
    detail = models.CharField(max_length=20, verbose_name='Detail', null=True, blank=True)

    members = models.ManyToManyField(Member, through='Takes_part_in_duty',
                                     through_fields=('duty', 'member'), )

    class Meta:
        verbose_name_plural = 'Dienste'
        verbose_name = 'Dienste'

    def __unicode__(self):
        return unicode(self.duty_number) + ' ' + unicode(self.duty_area.name)

    def getAEKcount(self):
        return self.members.filter(status='AEK').count()

    def is_closed(self):
        return (self.duty_start - timezone.now()).days < 15


class Takes_part_in_duty(models.Model):
    duty = models.ForeignKey(Duty, on_delete=models.CASCADE)
    member = models.ForeignKey(Member, on_delete=models.CASCADE)
    from_time = models.DateTimeField(verbose_name='Von')
    to_time = models.DateTimeField(verbose_name='Bis')
    function = models.ForeignKey(Dutyrole, on_delete=models.CASCADE, null=True, blank=True, verbose_name='Funktion')
    comment = models.TextField(verbose_name='Kommentar', max_length=200, blank=True)

    class Meta:
        verbose_name_plural = 'Dienstteilnahmen'
        verbose_name = 'Dienstteilnahme'

    def __unicode__(self):
        return unicode(self.duty) + ' - ' + unicode(self.member.user.username)

Bergwacht-System/BergwachtSystem/member_administration/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from datetime import date
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver

STATUS_CHOICES = (
    ('AEK', 'Aktive Einsatzkraft'),
    ('ANW', 'Anwärter'),
    ('NEK', 'Nicht-aktive Einsatzkraft'),
)


class DutyGroup(models.Model):
    name = models.CharField(max_length=20, verbose_name='Name')

    # primary_duty_area = models.ForeignKey(Dutyarea, null=True, blank=True)

    class Meta:
        verbose_name_plural = 'Trupps'
        verbose_name = 'Trupp'

    def __unicode__(self):
        return self.name


# Defines am Member of the Bergwacht with personal data
class Member(models.Model):
    # Link to the user-profile
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    # Personal Data
    mobile = models.CharField(max_length=20, verbose_name='Handynummer', null=True, blank=True)
    adress_street = models.CharField(max_length=100, verbose_name='Straße & Hnr.', null=True, blank=True)
    adress_plz = models.CharField(max_length=6, verbose_name='PLZ', null=True, blank=True)
    adress_city = models.CharField(max_length=100, verbose_name='Stadt', null=True, blank=True)
    birthdate = models.DateField(verbose_name='Geburtsdatum', null=True, blank=True)
    bw_join = models.DateField(verbose_name='Bergwacht-Eintritt', null=True, blank=True)
    status = models.CharField(max_length=3, choices=STATUS_CHOICES, default='ANW')
    dutygroups = models.ManyToManyField(DutyGroup, through='Members_in_Dutygroup',
                                        through_fields=('member', 'dutygroup'), related_name='dutygroups')
    trainings = models.ManyToManyField('trainings.Training', through='trainings.Member_Trainings', through_fields=('member', 'training'),
                                       related_name='trainings')

    avatar = models.ImageField(verbose_name='Portrait', null=True, blank=True)

    class Meta:
        verbose_name_plural = 'Mitglieder'
        ordering = ['status', 'user__last_name']

    def __unicode__(self):
        if not self.user.last_name:
            return self.user.username
        else:
            return self.user.last_name + ', ' + self.user.first_name

    def isAnwaerter(self):
        return self.status == 'ANW'

    def isAEK(self):
        return self.status == 'AEK'

    # Calculate Age of a Member 
    def getAge(self):
        age = 0;
        today = date.today()
        if self.birthdate != None:
            age = today.year - self.birthdate.year - (
                    (today.month, today.day) < (self.birthdate.month, self.birthdate.day))
        return age


# Qualifications of a Member
class Qualification(models.Model):
    name = models.CharField(primary_key=True, max_length=40, verbose_name='Name')

    class Meta:
        verbose_name_plural = 'Qualifikation'

    def __unicode__(self):
        return self.name


# Connection of Members and Qualifications
class MemberHasQualification(models.Model):
    member = models.ForeignKey(Member, on_delete=models.CASCADE, verbose_name='Mitglied')
    qualification = models.ForeignKey(Qualification, on_delete=models.CASCADE, verbose_name='Qualifikation')
    date = models.DateField(verbose_name='Datum', null=True, blank=True)

    class Meta:
        verbose_name_plural = 'Qualifikationen von Mitgliedern'

    def __unicode__(self):
        return self.member.user.username + '-' + self.qualification.name


class Members_in_Dutygroup(models.Model):
    member = models.ForeignKey(Member, on_delete=models.CASCADE, verbose_name='Mitglied')
    dutygroup = models.ForeignKey(DutyGroup, on_delete=models.CASCADE, verbose_name='Trupp')

    class Meta:
        verbose_name_plural = 'Truppmitgliedschaft'

    def __unicode__(self):
        return unicode(self.member) + '-' + unicode(self.dutygroup)


# Creates a Member object if new User is created
@receiver(post_save, sender=User)
def create_member(sender, instance, created, **kwargs):
    if created:
        Member.objects.create(user=instance)

Bergwacht-System/BergwachtSystem/duty_scheduler/forms.py
from django import forms
from .fields import DateTimePickerField
from .models import Takes_part_in_duty


class Duty_signup_form(forms.ModelForm):
    class Meta:
        model = Takes_part_in_duty
        exclude = ['duty', 'member', ]
        field_classes = {
            'from_time': DateTimePickerField,
            'to_time': DateTimePickerField,
        }

    def __init__(self, *args, **kwargs):
        super(Duty_signup_form, self).__init__(*args, **kwargs)

Bergwacht-System/BergwachtSystem/duty_scheduler/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.utils import timezone
from django.shortcuts import render, redirect

from .forms import Duty_signup_form
from .models import Duty, Member, Takes_part_in_duty


@login_required
def duty_list(request):
    duty_list = Duty.objects.filter(duty_start__gte =  timezone.now()).order_by('duty_start', 'duty_area')
    return render(request, 'duty_scheduler/duty_list.html',
                  {'duty_list': duty_list, 'current_member': Member.objects.get(user=request.user), 'show_all': False})


@login_required
def duty_list_all(request):
    duty_list = Duty.objects.order_by('duty_start', 'duty_area')
    return render(request, 'duty_scheduler/duty_list.html',
                  {'duty_list': duty_list, 'current_member': Member.objects.get(user=request.user), 'show_all': True})


@login_required
def duty_detail(request, duty_number):
    try:
        duty = Duty.objects.get(duty_number=duty_number)
        current_member = Member.objects.get(user=request.user)
        duty.members.order_by('-status', 'user__last_name')
    except Duty.DoesNotExist:
        raise Http404("Dienst existiert nicht")
    return render(request, 'duty_scheduler/duty_detail.html', {'duty': duty, 'current_member': current_member})


@login_required
def duty_calendar(request):
    duty_list = Duty.objects.all()
    return render(request, 'duty_scheduler/duty_calendar.html',
                  {'duty_list': duty_list, 'current_member': Member.objects.get(user=request.user)})


@login_required
def duty_signin(request, duty_number):
    try:
        duty = Duty.objects.get(duty_number=duty_number)
    except Duty.DoesNotExist:
        raise Http404("Dienst existiert nicht")

    error_message = ''
    if request.method == "POST":
        form = Duty_signup_form(request.POST)
        if form.is_valid():
            signup = form.save(commit=False)
            signup.member = Member.objects.get(user=request.user)
            signup.duty = duty
            if signup.from_time < signup.to_time and signup.member != duty.members.all:
                if signup.from_time >= duty.duty_start or signup.to_time <= duty.duty_end:
                    signup.save()
                    return redirect('duty_scheduler:duty_detail', duty_number=duty_number)
                else:
                    error_message = 'Anmeldezeitraum muss innerhalb des Dienstzeitraums liegen'
            else:
                error_message = 'Abmeldezeit muss nach Anmeldezeit liegen'

    else:
        form = Duty_signup_form(initial={'from_time': duty.duty_start, 'to_time': duty.duty_end})
    return render(request, 'duty_scheduler/duty_register.html',
                  {'form': form, 'duty': duty, 'error_message': error_message})


@login_required
def duty_signout(request, duty_number):
    user = request.user
    member = Member.objects.get(user=user)
    duty = Duty.objects.get(duty_number=duty_number)
    Takes_part_in_duty.objects.get(duty=duty, member=member).delete()
    return duty_list(request)

Bergwacht-System/BergwachtSystem/duty_scheduler/templates/duty_scheduler/duty_detail.html
{% extends 'base.html' %}

{% if  duty %}
{% block title %} Dienstplan - Eintrag Nr. {{ duty.duty_number }} {% endblock %}

{% block content %}
<div class="page-header">
    <h2>Dienstplan - Eintrag Nr. {{ duty.duty_number }}</h2>
</div>
<div class="row">
    <div class="col-md-9">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Aktionen</h3>
            </div>
            <table class="table table-bordered">
                <tr>
                    <td><b>Dienstgebiet</b></td>
                    <td>{{ duty.duty_area }}</td>
                </tr>
                <tr>
                    <td><b>Dienstbeginn</b></td>
                    <td>{{ duty.duty_start }}</td>
                </tr>
                <tr>
                    <td><b>Dienstende</b></td>
                    <td>{{ duty.duty_end }}</td>
                </tr>
                <tr>
                    <td><b>Dienstauftrag</b></td>
                    <td>{{ duty.category }} {% if not duty.detail is null %}({{ duty.detail }}){% endif %}</td>
                </tr>
                <tr>
                    <td><b>Teilnehmer</b></td>
                    <td>
                        <div class="progress">
                            {% if duty.getAEKcount == 0 %}
                            <div class="progress-bar progress-bar progress-bar-danger" role="progressbar"
                                 aria-valuenow="{{ duty.getAEKcount }}*100%/{{ duty.minaek }}" aria-valuemin="0"
                                 aria-valuemax="100" style="min-width: 2em; width: 0%;">
                                0/{{ duty.minaek }}
                            </div>
                            {% elif duty.getAEKcount >= duty.minaek %}
                            <div class="progress-bar progress-bar progress-bar-success" role="progressbar"
                                 aria-valuenow="100%" aria-valuemin="0"
                                 aria-valuemax="100" style="min-width: 2em; width: 100%;">
                                {{ duty.getAEKcount }}/{{ duty.minaek }}
                            </div>
                            {% else %}
                            <div class="progress-bar" role="progressbar"
                                 aria-valuenow="{{ duty.getAEKcount }}*100%/{{ duty.minaek }}" aria-valuemin="0"
                                 aria-valuemax="100"
                                 style="min-width: 2em; width: calc({{ duty.getAEKcount }}*100%/{{ duty.minaek }});">
                                {{ duty.getAEKcount }}/{{ duty.minaek }}
                            </div>
                            {% endif %}
                        </div>
                        <table class="table">
                            <tr>
                                <th>Name</th>
                                <th>Funktion</th>
                                <th>Von - Bis</th>
                                <th>Kontakt</th>
                                <th>Bemerkung</th>
                            </tr>
                            {% for takes_part in duty.takes_part_in_duty_set.all|dictsort:"member.status" %}
                            <tr>
                                <td>
                                    <a href="{% url 'member_administration:member_detail' takes_part.member.user.username %}">
                                        {{ takes_part.member.user.first_name }}
                                        {{ takes_part.member.user.last_name }}</a>
                                    <br>{{ takes_part.member.get_status_display }}
                                </td>
                                <td>{% if not takes_part.function is null %}{{ takes_part.function }}{% endif %}</td>
                                <td>{{ takes_part.from_time|date:'d.m.Y (H:i)' }} -
                                    <br>{{ takes_part.to_time|date:'d.m.Y (H:i)'}}
                                </td>
                                <td><a href="tel:{{ takes_part.member.mobile }}" class="btn btn-primary btn-sm"
                                       role="button">Anrufen</a>
                                    <a href="mailto:{{ takes_part.member.user.email }}" class="btn btn-primary btn-sm"
                                       role="button">Mail</a>
                                </td>
                                <td>{{ takes_part.comment }}</td>
                            </tr>
                            {% endfor %}
                        </table>
                    </td>
                </tr>
                <tr>
                    <td><b>Bemerkung</b></td>
                    <td>{{ duty.bemerkung }}</td>
                </tr>
            </table>
        </div>
    </div>
    <div class="col-md-3">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Aktionen</h3>
            </div>
            <div class="btn-group-vertical btn-block" role="group">
                <a href="mailto: {% for member in  duty.members.all %}{{ member.user.email }}, {% endfor %}"
                   class="btn btn-success">Mail an alle Teilnehmer</a>

                {% if current_member in duty.members.all %}
                <a href="{% url 'duty_scheduler:duty_signout' duty.duty_number %}"
                   class="btn btn-danger"
                   role="button">Abmelden</a>
                {% else %}
                <a href="{% url 'duty_scheduler:duty_signin' duty.duty_number %}" class="btn btn-primary"
                   role="button">Anmelden</a>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% else %}
<p>Dienst nicht hinterlegt!</p>
{% endif %}

Bergwacht-System/BergwachtSystem/duty_scheduler/templates/duty_scheduler/duty_list.html
{% extends 'base.html' %}

{% if duty_list %}

{% block title %} Dienstplan {% endblock %}

{% block content %}
<h1>Dienstplan</h1>

<ul class="nav nav-tabs nav-justified">
    <li role="presentation" class="active"><a href="#"> Liste </a></li>
    <li role="presentation"><a href="{% url 'duty_scheduler:duty_calendar' %}"> Kalender </a></li>
</ul>

<div class="col-12">
    <p>
    {% if show_all %}
    <a href="{% url 'duty_scheduler:duty_list' %}" class="btn btn-default btn-block">
        Nur zukünftige
    </a>
    {% else %}
    <a href="{% url 'duty_scheduler:duty_list_all' %}" class="btn btn-default btn-block">
        Zeige alle
    </a>
    {%  endif %}
    </p>
</div>

<div class="hidden-xs">
    <div class="table-responsive">
        <table class="table table-striped table-bordered">
            <tr>
                <th>Gebiet</th>
                <th>Beginn</th>
                <th>Ende</th>
                <th>Art</th>
                <th>#AEK</th>
                <th>Einsatzkräfte</th>
                <th>Andere</th>
                <th>Aktion</th>
            </tr>
            {% for duty in duty_list %}
            <tr>
                <td>{% if duty.duty_area.link %}
                    <a href="{{ duty.duty_area.link }}">{{ duty.duty_area.name }}</a>
                    {% else %}
                    {{ duty.duty_area.name }}
                    {% endif %}
                </td>
                <td>{{ duty.duty_start|date:'d.m.Y' }}<br>{{ duty.duty_start|date:'H:i' }}</td>
                <td>{{ duty.duty_end|date:'d.m.Y' }}<br>{{ duty.duty_end|date:'H:i' }}</td>
                <td>{{ duty.category }}<br>{% if not duty.detail is null %}{{ duty.detail }}{% endif %}
                </td>
                <td>
                    <div class="progress">
                        {% if duty.getAEKcount == 0 %}
                        <div class="progress-bar progress-bar progress-bar-danger" role="progressbar"
                             aria-valuenow="{{ duty.getAEKcount }}*100%/{{ duty.minaek }}" aria-valuemin="0"
                             aria-valuemax="100" style="min-width: 2em; width: 0%;">
                            0/{{ duty.minaek }}
                        </div>
                        {% elif duty.getAEKcount >= duty.minaek %}
                        <div class="progress-bar progress-bar progress-bar-success" role="progressbar"
                             aria-valuenow="100%" aria-valuemin="0"
                             aria-valuemax="100" style="min-width: 2em; width: 100%;">
                            {{ duty.getAEKcount }}/{{ duty.minaek }}
                        </div>
                        {% else %}
                        <div class="progress-bar" role="progressbar"
                             aria-valuenow="{{ duty.getAEKcount }}*100%/{{ duty.minaek }}" aria-valuemin="0"
                             aria-valuemax="100"
                             style="min-width: 2em; width: calc({{ duty.getAEKcount }}*100%/{{ duty.minaek }});">
                            {{ duty.getAEKcount }}/{{ duty.minaek }}
                        </div>
                        {% endif %}
                    </div>
                </td>
                <td>{% for takes_part in duty.takes_part_in_duty_set.all %}
                    {% if takes_part.member.isAEK %}
                    <a href="{% url 'member_administration:member_detail' takes_part.member.user.username %}">
                        {{ takes_part.member.user.first_name}} {{ takes_part.member.user.last_name }}</a>
                    {% if takes_part.function != None %} ({{ takes_part.function.shortname }}) {% endif %}
                    <br>
                    {% endif %}
                    {% endfor %}
                </td>
                <td> {% for takes_part in duty.takes_part_in_duty_set.all %}
                    {% if not takes_part.member.isAEK %}
                    <a href="{% url 'member_administration:member_detail' takes_part.member.user.username %}">
                        {{ takes_part.member.user.first_name }} {{ takes_part.member.user.last_name }}</a>
                    {% if takes_part.function != None %} ({{ takes_part.function.shortname }}) {% endif %}
                    <br>
                    {% endif %}
                    {% endfor %}
                </td>
                <td>
                    <a href="{% url 'duty_scheduler:duty_detail' duty.duty_number %}" class="btn btn-default"
                       role="button"><span class="glyphicon glyphicon-info-sign"
                                           aria-hidden="true"></span></a>
                    {% if current_member in duty.members.all %}
                    <a href="{% url 'duty_scheduler:duty_signout' duty.duty_number %}"
                       class="btn btn-danger {% if duty.is_closed %}disabled{% endif %}"
                       role="button">Abmelden</a>
                    {% else %}
                    <a href="{% url 'duty_scheduler:duty_signin' duty.duty_number %}"
                       class="btn btn-primary {% if duty.is_closed %}disabled{% endif %}"
                       role="button">Anmelden</a>
                    {% endif %}
                    <!-- <a href="mailto: {% for member in duty.members.all %}{{ member.user.email }}, {% endfor %} "
                       class="btn btn-success" role="button">Mail</a> -->
                </td>
            </tr>
            {% endfor %}
        </table>
    </div>
</div>


<div class="visible-xs">
    {% for duty in duty_list %}
    <div class="panel panel-default">
        <!-- Default panel contents -->
        <div class="panel-heading">
            <h2 class="panel-title">
                {{ duty.duty_area.name }} - {{ duty.duty_start|date:'d. M. Y' }}
            </h2>
        </div>
        <div class="panel-body">
            <div class="col-xs-9">
                {{ duty.duty_start|date:'d.m.Y (H:i)' }} - {{ duty.duty_end|date:'d.m.Y (H:i)' }}<br>
                {{ duty.category }}
            </div>
            <div class="col-xs-3">
                {% if current_member in duty.members.all %}
                <a href="{% url 'duty_scheduler:duty_signout' duty.duty_number %}"
                   class="btn btn-danger {% if duty.is_closed %}disabled{% endif %}"
                   role="button">Abmelden</a>
                {% else %}
                <a href="{% url 'duty_scheduler:duty_signin' duty.duty_number %}"
                   class="btn btn-primary {% if duty.is_closed %}disabled{% endif %}"
                   role="button">Anmelden</a>
                {% endif %}
            </div>
        </div>
    </div>
    {% endfor %}
</div>


{% endblock %}
{% else %}
<p>Keine aktuellen Dienste angelegt!</p>
{% endif %}

Bergwacht-System/BergwachtSystem/duty_scheduler/templates/duty_scheduler/duty_register.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load static %}
{% load bootstrap3 %}

{% block title %} Anmeldung zum Dienst Nr. {{ dienst.dienstnummer }} {% endblock %}
{% if duty %}

{% block content %}
<h2>Anmeldung zum Dienst Nr. {{ duty.duty_number }}</h2>


<form action="" method="post">
    {% csrf_token %}

    <div id="content" class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
        {{ duty.duty_start|date:'d.m.Y (H:i)' }} - {{ duty.duty_end|date:'d.m.Y (H:i)' }}

        {% bootstrap_form_errors form %}
        {% bootstrap_form form %}

        <input type="submit" value="Anmelden" class="btn btn-default"/>
    </div>
</form>

<script type="text/javascript">
        $(function () {
            $('.datetime').parent().datetimepicker({
                locale: 'de',
                format: 'DD.MM.YYYY HH:mm',
            });
        });
</script>

{{ error_message }}

{% endblock %}

{% else %}
<p>Dienst nicht hinterlegt!</p>
{% endif %}