Bergwacht-System/BergwachtSystem/BergwachtSystem/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView

admin.autodiscover()

urlpatterns = [
                  url(r'^login/$', auth_views.login, name='login'),
                  url(r'^logout/$', auth_views.logout, name='logout'),
                  url(r'^admin/', include(admin.site.urls)),
                  url(r'^start/$', TemplateView.as_view(template_name='start.html'), name='start'),
                  url(r'^mitglieder/', include('member_administration.urls')),
                  url(r'^dienstplan/', include('duty_scheduler.urls')),
                  url(r'^ausbildung/', include('trainings.urls')),
                  url(r'^', include('cms.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Bergwacht-System/BergwachtSystem/duty_scheduler/urls.py
from django.conf.urls import url

from . import views

app_name = 'duty_scheduler'

urlpatterns = [
    url(r'^$', views.duty_list, name='duty_list'),
    url(r'^all/$', views.duty_list_all, name='duty_list_all'),
    url(r'^calendar/$', views.duty_calendar, name='duty_calendar'),
    url(r'^(?P<duty_number>[0-9]+)/$', views.duty_detail, name='duty_detail'),
    url(r'^anmeldung/(?P<duty_number>[0-9]+)/$', views.duty_signin, name='duty_signin'),
    url(r'^abmeldung/(?P<duty_number>[0-9]+)/$', views.duty_signout, name='duty_signout'),
]

Bergwacht-System/BergwachtSystem/member_administration/urls.py
from django.conf.urls import url

from . import views

app_name = 'member_administration'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<username>[a-z]+)/$', views.member_detail, name='member_detail'),
]

Bergwacht-System/BergwachtSystem/trainings/urls.py
from __future__ import unicode_literals
from django.conf.urls import url

from . import views

app_name = 'trainings'

urlpatterns = [
    url(r'^$', views.training_overview, name='training_overview'),
    url(r'^liste/$', views.training_list, name='training_list'),
    url(r'^termine/$', views.training_dates, name='training_dates'),
    url(r'^zeitmeldung/(?P<training_event_id>[0-9]+)/$', views.register_time_for_training,
        name='register_time_for_training'),
    url(r'^zeitabmeldung/(?P<training_event_id>[0-9]+)/$', views.deregister_time_for_training,
        name='deregister_time_for_training'),
    url(r'^zeitabmeldung/(?P<training_event_id>[0-9]+)/(?P<username>[a-z]+)/$', views.deregister_user_time_for_training,
        name='deregister_user_time_for_training'),
    url(r'^freischalten/(?P<training_event_id>[0-9]+)/$', views.permit_for_training,
        name='permit_for_training'),
    url(r'^anmeldung/(?P<training_event_id>[0-9]+)/(?P<username>[a-z]+)/$', views.register_for_training,
        name='register_for_training'),
    url(r'^abmeldung/(?P<training_event_id>[0-9]+)/(?P<username>[a-z]+)/$', views.deregister_for_training,
        name='deregister_for_training'),
    url(r'^teilnahmeeintragen/(?P<training_event_id>[0-9]+)/$', views.accept_member_trainings,
        name='accept_member_trainings'),
    url(r'^teilnahmeeintragen/(?P<training_event_id>[0-9]+)/(?P<username>[a-z]+)/$', views.register_member_training,
        name='register_member_training'),
]

Bergwacht-System/BergwachtSystem/templates/base.html
{% load cms_tags sekizai_tags %}
{% load static %}
{% load bootstrap3 %}
{% load menu_tags %}

<!DOCTYPE html>
<html lang="de">
<head>

    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    {% bootstrap_css %}
    {% bootstrap_javascript %}

    {# jquery #}
    <script src="{% static 'jquery/jquery.min.js' %}"></script>

    {# bootstrap3 #}
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.css' %}" media="all">
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap-theme.css' %}" media="all">
    <script type="text/javascript" src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'bootstrap/js/transition.js' %}"></script>
    <script type="text/javascript" src="{% static 'bootstrap/js/collapse.js' %}"></script>

    {# moment.js #}
    <script src="{% static 'momentjs/moment-with-locales.min.js' %}"></script>

    {# Date-Time-Picker #}
    <link href="{% static 'bootstrap-datetimepicker/css/bootstrap-datetimepicker.min.css' %}" media="all"
          rel="stylesheet">
    <script type="text/javascript"
            src="{% static 'bootstrap-datetimepicker/js/bootstrap-datetimepicker.min.js' %}"></script>

    {# DataTables #}
    <link href="{% static 'datatables/jquery.dataTables.min.css' %}" media="all" rel="stylesheet">
    <link href="{% static 'datatables/dataTables.bootstrap.min.css' %}" media="all" rel="stylesheet">
    <script type="text/javascript" src="{% static 'datatables/jquery.dataTables.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'datatables/dataTables.bootstrap.min.js' %}"></script>


    {# Own Additions #}
    <script type="text/javascript" src="{% static 'bootstrap/js/addition.js' %}"></script>
    <link rel="stylesheet" href="{% static 'bootstrap/css/addition.css' %}">


    <title>Bergwacht München - {% page_attribute "page_title" %}</title>
    {% render_block "css" %}
    {% show_menu 0 100 0 100 "menu.html" %}
    <!-- django CMS toolbar adjustment -->
    {% if request.toolbar %}
    <style>
    .cms-toolbar-expanded .navbar {
        margin-top: 45px;
    }
    </style>
    {% endif %}
</head>
<body>
<div id="content" class="col-xs-12 col-sm-12 col-md-12">
    {% cms_toolbar %}
    <div class="container">
        {% block content %}{% endblock %}
        {% render_block "js" %}
    </div>
</div>
<div class="container">
    {% static_placeholder 'footer' %}
</div>
</body>
</html>

Bergwacht-System/BergwachtSystem/templates/home.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% load cms_tags %}
{% load menu_tags %}
{% load static %}

{% block content %}

<div class="row">
    <ul class="nav nav-tabs nav-justified">
        {% for child in children %}
        <li role="presentation"><a href="{{ child.attr.redirect_url|default:child.get_absolute_url }}"
                                   class="list-group-item child {% if child.selected %}active selected{% endif %} {% if child.ancestor %}ancestor{% endif %} {% if child.sibling %}sibling{% endif %} {% if child.descendant %}descendant{% endif %}">
            <b>{{ child.get_menu_title }}</b></a></li>
        {% endfor %}
    </ul>
</div>
<div class="row">
 &nbsp;
</div>

<div class="row">
    <div class="col-md-3">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Menü</h3>
            </div>
            <div class="list-group">
                {% for child in children %}
                {% if child.children %}
                {% for child2 in child.children %}
                <a href="{{ child2.attr.redirect_url|default:child2.get_absolute_url }}"
                   class="list-group-item child {% if child2.selected %}active selected{% endif %} {% if child2.ancestor %}ancestor{% endif %} {% if child2.sibling %}sibling{% endif %} {% if child2.descendant %}descendant{% endif %}">
                    <span class="glyphicon glyphicon-menu-right" aria-hidden="true"></span> {{ child2.get_menu_title }}</a>

                {% if child2.children %}
                {% for child3 in child2.children %}
                <a href="{{ child3.attr.redirect_url|default:child3.get_absolute_url }}"
                   class="list-group-item child {% if child3.selected %}active selected{% endif %} {% if child3.ancestor %}ancestor{% endif %} {% if child3.sibling %}sibling{% endif %} {% if child3.descendant %}descendant{% endif %}">
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="glyphicon glyphicon-menu-right" aria-hidden="true"></span> {{ child3.get_menu_title }}</a>
                {% endfor %}
                {% endif %}

                {% endfor %}
                {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
    <div class="col-md-9">
        {% placeholder "feature" %}
        {% placeholder "content" %}
        {% placeholder "splashbox" %}
    </div>
</div>
{% endblock %}

Bergwacht-System/BergwachtSystem/templates/menu.html
{% load menu_tags %}
{% load static %}


<nav class="navbar navbar-bergwacht navbar-fixed-top">
    <div class="container-fluid">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="collapsed navbar-toggle" data-toggle="collapse"
                        data-target="#bs-example-navbar-collapse-6" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="{% url 'start' %}" class="navbar-brand"><img src="{% static 'img/Logo-253-comp.jpg' %}"
                                                                      alt="BW München"
                                                                      height="40px"></a>
                <a href="{% url 'start' %}" class="navbar-brand">Bergwacht München</a>
            </div>

            {% if user.is_authenticated %}
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-6">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="/"><span class="glyphicon glyphicon-home"
                                          aria-hidden="true"></span>
                            Informationen</a>
                    </li>
                    <li>
                        <a href="{% url 'member_administration:index' %}"><span class="glyphicon glyphicon-user"
                                                                                aria-hidden="true"></span>
                            Mitglieder</a>
                    </li>
                    <li>
                        <a href="{% url 'duty_scheduler:duty_list' %}"><span class="glyphicon glyphicon-calendar"
                                                                             aria-hidden="true"></span>
                            Dienstplan</a>
                    </li>
                    <li>
                        <a href="{% url 'trainings:training_overview' %}"><span class="glyphicon glyphicon-education"
                                                                                aria-hidden="true"></span>
                            Ausbildung</a>
                    </li>
                </ul>
                {% else %}
                <p class="navbar-text">
                    Intranet - Nur für angemeldete Nutzer
                </p>
                {% endif %}

                <p class="navbar-text navbar-right">
                    {% if user.is_authenticated %}
                    Angemeldet als {{request.user.first_name}} {{request.user.last_name}}

                    {% if user.is_superuser %}
                    {% if request.toolbar.build_mode or request.toolbar.edit_mode %}
                    <a href="?toolbar_off" class="btn btn-success"><span class="glyphicon glyphicon-wrench"
                                                                         aria-hidden="true"></span></a>
                    {% else %}
                    <a href="?edit" class="btn btn-primary"><span class="glyphicon glyphicon-wrench"
                                                                         aria-hidden="true"></span></a>
                    {% endif %}
                    {% endif %}

                    <a href="/logout/" class="btn btn-default">Logout</a>
                    {% else %}
                    <a href="/login/" class="btn btn-default">Login</a>
                    {% endif %}
                </p>
            </div>
        </div>
    </div>
</nav>

Bergwacht-System/BergwachtSystem/templates/start.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="page-header">
    <h1>Intranet der Bergwacht München</h1>
</div>


<div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
    <div class="list-group">
        <a href="/" class="list-group-item"><span class="glyphicon glyphicon-home" aria-hidden="true"></span>
            Informationen</a>
        <a href="{% url 'member_administration:index' %}" class="list-group-item"><span class="glyphicon glyphicon-user"
                                                                                        aria-hidden="true"></span>
            Mitglieder</a>
        <a href="{% url 'duty_scheduler:duty_list' %}" class="list-group-item"><span
                class="glyphicon glyphicon-calendar" aria-hidden="true"></span> Dienstplan</a>
        <a href="{% url 'trainings:training_overview' %}" class="list-group-item"><span
                class="glyphicon glyphicon-education" aria-hidden="true"></span> Ausbildung</a>
    </div>
</div>
{% endblock %}