Bergwacht-System/BergwachtSystem/BergwachtSystem/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView

admin.autodiscover()

urlpatterns = [
                  url(r'^login/$', auth_views.login, name='login'),
                  url(r'^logout/$', auth_views.logout, name='logout'),
                  url(r'^admin/', include(admin.site.urls)),
                  url(r'^start/$', TemplateView.as_view(template_name='start.html'), name='start'),
                  url(r'^mitglieder/', include('member_administration.urls')),
                  url(r'^dienstplan/', include('duty_scheduler.urls')),
                  url(r'^ausbildung/', include('trainings.urls')),
                  url(r'^', include('cms.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Bergwacht-System/BergwachtSystem/member_administration/urls.py
from django.conf.urls import url

from . import views

app_name = 'member_administration'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<username>[a-z]+)/$', views.member_detail, name='member_detail'),
]

Bergwacht-System/BergwachtSystem/trainings/urls.py
from __future__ import unicode_literals
from django.conf.urls import url

from . import views

app_name = 'trainings'

urlpatterns = [
    url(r'^$', views.training_overview, name='training_overview'),
    url(r'^liste/$', views.training_list, name='training_list'),
    url(r'^termine/$', views.training_dates, name='training_dates'),
    url(r'^zeitmeldung/(?P<training_event_id>[0-9]+)/$', views.register_time_for_training,
        name='register_time_for_training'),
    url(r'^zeitabmeldung/(?P<training_event_id>[0-9]+)/$', views.deregister_time_for_training,
        name='deregister_time_for_training'),
    url(r'^zeitabmeldung/(?P<training_event_id>[0-9]+)/(?P<username>[a-z]+)/$', views.deregister_user_time_for_training,
        name='deregister_user_time_for_training'),
    url(r'^freischalten/(?P<training_event_id>[0-9]+)/$', views.permit_for_training,
        name='permit_for_training'),
    url(r'^anmeldung/(?P<training_event_id>[0-9]+)/(?P<username>[a-z]+)/$', views.register_for_training,
        name='register_for_training'),
    url(r'^abmeldung/(?P<training_event_id>[0-9]+)/(?P<username>[a-z]+)/$', views.deregister_for_training,
        name='deregister_for_training'),
    url(r'^teilnahmeeintragen/(?P<training_event_id>[0-9]+)/$', views.accept_member_trainings,
        name='accept_member_trainings'),
    url(r'^teilnahmeeintragen/(?P<training_event_id>[0-9]+)/(?P<username>[a-z]+)/$', views.register_member_training,
        name='register_member_training'),
]

Bergwacht-System/BergwachtSystem/trainings/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.utils import timezone
from django.db import models
from member_administration.models import Member


class TrainingCategory(models.Model):
    name = models.CharField(primary_key=True, max_length=50, verbose_name='Name')

    class Meta:
        verbose_name_plural = 'Ausbildungskategorien'
        verbose_name = 'Ausbildungskategorie'

    def __unicode__(self):
        return self.name


class Training(models.Model):
    name = models.CharField(primary_key=True, max_length=50, verbose_name='Name')
    prerequisites = models.ManyToManyField("self", through='Prerequisites_for_training',
                                           through_fields=('post_training', 'pre_training'),
                                           verbose_name='Voraussetzungen',
                                           symmetrical=False,
                                           related_name='with_prerequisite')
    category = models.ForeignKey(TrainingCategory, on_delete=models.CASCADE, verbose_name='Kategorie', null=True)

    class Meta:
        verbose_name_plural = 'Ausbildungen'
        verbose_name = 'Ausbildung'

    def __unicode__(self):
        return self.name


class Prerequisites_for_training(models.Model):
    pre_training = models.ForeignKey(Training, on_delete=models.CASCADE, related_name='pre_training',
                                     verbose_name='Voraussetzung', null=True)
    post_training = models.ForeignKey(Training, on_delete=models.CASCADE, related_name='post_training',
                                      verbose_name='Für Ausbildung', null=True)

    class Meta:
        verbose_name_plural = 'Ausbildungsvoraussetzungen'
        verbose_name = 'Ausbildungsvoraussetzung'

    def __unicode__(self):
        return unicode(self.pre_training) + ' > ' + unicode(self.post_training)


class TrainingEvent(models.Model):
    training_event_id = models.AutoField(primary_key=True)
    training = models.ForeignKey(Training, verbose_name='Ausbildung')
    event_start = models.DateTimeField(verbose_name='Beginn')
    event_end = models.DateTimeField(verbose_name='Ende')
    max_member = models.IntegerField(verbose_name='Max. Teilnehmerzahl')

    direct_registration = models.BooleanField(verbose_name="Direktanmeldung möglich", default=True)

    trainer = models.ManyToManyField(Member, related_name='trainer')
    participants = models.ManyToManyField(Member, through='Participates_in_trainingevent',
                                          through_fields=('trainingevent', 'member'), related_name='participants')
    possible_participants = models.ManyToManyField(Member, through='Possible_participates_in_trainingevent',
                                                   through_fields=('trainingevent', 'member'),
                                                   related_name='possible_participants')

    class Meta:
        verbose_name_plural = 'Ausbildungstermine'
        verbose_name = 'Ausbildungstermin'

    def __unicode__(self):
        return unicode(self.training.name) + ' - ' + unicode(self.event_start)

    def getMemberCount(self):
        return self.participants.count()


class Participates_in_trainingevent(models.Model):
    trainingevent = models.ForeignKey(TrainingEvent, on_delete=models.CASCADE)
    member = models.ForeignKey(Member, on_delete=models.CASCADE)
    comment = models.TextField(verbose_name='Kommentar', max_length=200, blank=True)
    first_register_timestamp = models.DateTimeField(verbose_name='Erste Anmeldung', editable=True, null=True)

    class Meta:
        verbose_name_plural = 'Teilnahmen an Ausbildungstermin'
        verbose_name = 'Teilnahme an Ausbildungstermin'

    def __unicode__(self):
        return unicode(self.trainingevent) + ' - ' + unicode(self.member)


class Possible_participates_in_trainingevent(models.Model):
    trainingevent = models.ForeignKey(TrainingEvent, on_delete=models.CASCADE)
    member = models.ForeignKey(Member, on_delete=models.CASCADE)
    comment = models.TextField(verbose_name='Kommentar', max_length=200, blank=True)
    first_register_timestamp = models.DateTimeField(default=timezone.now, verbose_name='Erste Anmeldung', editable=True,
                                                    null=True)

    class Meta:
        verbose_name_plural = 'Mögliche Teilnahmen an Ausbildungstermin'
        verbose_name = 'Mögliche Teilnahme an Ausbildungstermin'

    def __unicode__(self):
        return 'P - ' + unicode(self.trainingevent) + ' - ' + unicode(self.member)


class Member_Trainings(models.Model):
    member = models.ForeignKey(Member, on_delete=models.CASCADE, verbose_name='Mitglied')
    training = models.ForeignKey(Training, on_delete=models.CASCADE, verbose_name='Ausbildung')
    date = models.DateField(verbose_name='Datum', null=True, blank=True)

    class Meta:
        verbose_name_plural = 'Ausbildungen von Mitgliedern'
        verbose_name = 'Ausbildung von Mitglied'

    def __unicode__(self):
        return unicode(self.member) + '-' + unicode(self.training)

Bergwacht-System/BergwachtSystem/trainings/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.utils import timezone
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.models import User
from django.shortcuts import render, redirect

# Create your views here.
from member_administration.models import Member
from trainings.models import Training, TrainingEvent, Possible_participates_in_trainingevent, \
    Participates_in_trainingevent, Prerequisites_for_training, Member_Trainings


@login_required
def training_overview(request):
    return render(request, 'trainings/training_start.html', {'nav': 'start'})


@login_required
def training_list(request):
    training_list = Training.objects.order_by('name')
    return render(request, 'trainings/training_list.html',
                  {'training_list': training_list, 'current_member': Member.objects.get(user=request.user),
                   'nav': 'list'})


@login_required
def training_dates(request):
    training_events = TrainingEvent.objects.order_by('event_start')
    return render(request, 'trainings/training_dates.html',
                  {'training_events': training_events, 'current_member': Member.objects.get(user=request.user),
                   'nav': 'dates'})


@login_required
def register_time_for_training(request, training_event_id):
    currentMember = Member.objects.get(user=request.user)
    training_event = TrainingEvent.objects.get(training_event_id=training_event_id)
    Possible_participates_in_trainingevent.objects.create(
        member=currentMember,
        trainingevent=training_event,
        first_register_timestamp=timezone.now()
    )
    return redirect('/ausbildung/termine/')


@login_required
def deregister_time_for_training(request, training_event_id):
    member = Member.objects.get(user=request.user)
    training_event = TrainingEvent.objects.get(training_event_id=training_event_id)
    Possible_participates_in_trainingevent.objects.filter(member=member, trainingevent=training_event).delete()
    return redirect('/ausbildung/termine/')


@login_required
@user_passes_test(lambda u: u.has_perm('trainings.can_delete_possible_participates_in_trainingevent'))
def deregister_user_time_for_training(request, training_event_id, username):
    user = User.objects.get(username=username)
    member = Member.objects.get(user=user)
    training_event = TrainingEvent.objects.get(training_event_id=training_event_id)
    Possible_participates_in_trainingevent.objects.filter(member=member, trainingevent=training_event).delete()
    return redirect('/ausbildung/freischalten/' + unicode(training_event_id) + '/')


@login_required
@user_passes_test(lambda u: u.has_perm('trainings.can_add_participates_in_trainingevent'))
def register_for_training(request, training_event_id, username):
    user = User.objects.get(username=username)
    member = Member.objects.get(user=user)
    training_event = TrainingEvent.objects.get(training_event_id=training_event_id)

    possible_participates_in_trainingevent = Possible_participates_in_trainingevent.objects.get(member=member,
                                                                                                trainingevent=training_event)

    Participates_in_trainingevent.objects.create(
        member=member,
        trainingevent=training_event,
        first_register_timestamp=possible_participates_in_trainingevent.first_register_timestamp
    )
    possible_participates_in_trainingevent.delete()
    return redirect('/ausbildung/freischalten/' + unicode(training_event_id) + '/')


@login_required
@user_passes_test(lambda u: u.has_perm('trainings.can_add_participates_in_trainingevent'))
def deregister_for_training(request, training_event_id, username):
    user = User.objects.get(username=username)
    member = Member.objects.get(user=user)
    training_event = TrainingEvent.objects.get(training_event_id=training_event_id)

    participates_in_trainingevent = Participates_in_trainingevent.objects.get(member=member,
                                                                              trainingevent=training_event)

    Possible_participates_in_trainingevent.objects.create(
        member=member,
        trainingevent=training_event,
        first_register_timestamp=participates_in_trainingevent.first_register_timestamp
    )
    participates_in_trainingevent.delete()
    return redirect('/ausbildung/freischalten/' + unicode(training_event_id) + '/')


@login_required
@user_passes_test(lambda u: u.has_perm('trainings.can_add_participates_in_trainingevent'))
def permit_for_training(request, training_event_id):
    training_event = TrainingEvent.objects.get(training_event_id=training_event_id)
    possible_participants = Possible_participates_in_trainingevent.objects.filter(trainingevent=training_event)

    return render(request, 'trainings/training_permit.html',
                  {'training_event': training_event, 'nav': 'dates', 'possible_participants': possible_participants})


@login_required
@user_passes_test(lambda u: u.has_perm('trainings.can_add_member_trainings'))
def accept_member_trainings(request, training_event_id):
    training_event = TrainingEvent.objects.get(training_event_id=training_event_id)

    return render(request, 'trainings/training_accept_member_trainings.html',
                  {'nav': 'dates', 'training_event': training_event, })


@login_required
def register_member_training(request, training_event_id, username):
    user = User.objects.get(username = username)
    member = Member.objects.get(user = user)
    training_event = TrainingEvent.objects.get(training_event_id=training_event_id)
    Member_Trainings.objects.get_or_create(member=member, training=training_event.training, date=training_event.event_end.date())
    return redirect(
        '/ausbildung/teilnahmeeintragen/' + unicode(training_event_id) + '/')

Bergwacht-System/BergwachtSystem/trainings/templates/trainings/training_accept_member_trainings.html
{% extends 'training_base.html' %}


{% block title %} Ausbildungen {% endblock %}

{% block training_content %}
<div class="page-header">
    <h2>Ausbildung
        <small>Ausbildung für Teilnehmer eintragen</small>
    </h2>
</div>
<div class="row">
    <div class="col-md-9">
        <div class="panel panel-default">
            <!-- Default panel contents -->
            <div class="panel-heading">
                <h2 class="panel-title">
                    Ausbildung Details
                </h2>
            </div>
            <table class="table">
                {% for member in training_event.participants.all %}
                <tr>
                    <td><a href="{% url 'member_administration:member_detail' member.user.username %}">
                        {{ member.user.last_name }}, {{ member.user.first_name }}</a>
                    </td>
                    <td>
                        {% if training_event.training in member.trainings.all %}
                        <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
                        {% else %}
                        <a href="{% url 'trainings:register_member_training' training_event.training_event_id member.user.username %}"
                           class="btn btn-primary btn-xs"><span class="glyphicon glyphicon-ok"
                                                                aria-hidden="true"></span></a>
                        {% endif %}
                    </td>
                </tr>
                {% endfor %}
            </table>
        </div>
    </div>
    <div class="col-md-3">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Aktionen</h3>
            </div>
            <div class="btn-group-vertical btn-block" role="group">
                <a href="#"
                   class="btn btn-default">Alle eintragen</a>
                <a href="#"
                   class="btn btn-danger">Ausbildung schließen</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

Bergwacht-System/BergwachtSystem/trainings/templates/trainings/training_dates.html
{% extends 'training_base.html' %}

{% block title %} Ausbildungen {% endblock %}

{% block training_content %}
<div class="page-header">
    <h2>Ausbildung
        <small>Termine</small>
    </h2>
</div>
<div class="table-responsive">
    <table class="table table-bordered">
        <tr>
            <th>Ausbildung</th>
            <th>Beginn</th>
            <th>Ende</th>
            <th>Plätze</th>
            <th>Ausbilder</th>
            <th>Anmeldung</th>
            {% if perms.trainings.can_add_participates_in_trainingevent %}
            <th></th>
            {% endif %}
        </tr>
        {% for trainingevent in training_events %}
        <tr>
            <td>{{ trainingevent.training.name }}</td>
            <td>{{ trainingevent.event_start|date:'d.m.Y' }}<br>{{ trainingevent.event_start|date:'H:i' }}</td>
            <td>{{ trainingevent.event_end|date:'d.m.Y' }}<br>{{ trainingevent.event_end|date:'H:i' }}</td>
            <td>
                <div class="progress">
                    {% if trainingevent.getMemberCount <= trainingevent.max_member %}
                    <div class="progress-bar progress-bar progress-bar-success" role="progressbar"
                         aria-valuenow="{{ trainingevent.getMemberCount }}*100%/{{ trainingevent.minaek }}"
                         aria-valuemin="0"
                         aria-valuemax="100"
                         style="min-width: 2em; width: calc({{ trainingevent.getMemberCount }}*100%/{{ trainingevent.max_member }});">
                        {{ trainingevent.getMemberCount }}/{{ trainingevent.max_member }}
                    </div>
                    {% else %}
                    <div class="progress-bar progress-bar-danger" role="progressbar"
                         aria-valuenow="100%" aria-valuemin="0"
                         aria-valuemax="100"
                         style="min-width: 2em; width: 100%">
                        {{ trainingevent.getMemberCount }}/{{ trainingevent.max_member }}
                    </div>
                    {% endif %}
                </div>
            </td>
            <td>{% for trainer in trainingevent.trainer.all %}
                <a href="{% url 'member_administration:member_detail' trainer.user.username %}">
                    {{ trainer.user.first_name}} {{ trainer.user.last_name }}</a>
                <br>
                {% endfor %}
            </td>
            <td>
                {% if not trainingevent.direct_registration %}
                {% if current_member in trainingevent.possible_participants.all %}
                <a href="{% url 'trainings:deregister_time_for_training' trainingevent.training_event_id %}"
                   class="btn btn-danger"
                   role="button">Keine Zeit mehr</a>
                {% else %}
                {% if current_member in trainingevent.participants.all %}
                <a href="#" class="btn btn-success disabled" role="button">Angemeldet</a>
                {% else %}
                <a href="{% url 'trainings:register_time_for_training' trainingevent.training_event_id %}"
                   class="btn btn-primary"
                   role="button">Ich habe Zeit</a>
                {% endif %}
                {% endif %}
                {% else %}
                {% if current_member in trainingevent.participants.all %}
                <a href="#"
                   class="btn btn-danger"
                   role="button">Abmelden</a>
                {% else %}
                <a href="#" class="btn btn-primary"
                   role="button">Anmelden</a>
                {% endif %}
                {% endif %}
            </td>
            {% if perms.trainings.can_add_participates_in_trainingevent %}
            <td>
                <a href="{% url 'trainings:permit_for_training' trainingevent.training_event_id %}"
                   class="btn btn-default"><span class="glyphicon glyphicon-wrench"
                                                 aria-hidden="true"></span> <span class="badge">{{ trainingevent.possible_participants.all | length }}</span></a>
            </td>
            {% endif %}
        </tr>
        {% endfor %}
    </table>
</div>
{% endblock %}

Bergwacht-System/BergwachtSystem/trainings/templates/trainings/training_list.html
{% extends 'training_base.html' %}

{% block title %} Ausbildungen {% endblock %}
{% block training_content %}
<div class="page-header">
<h2>Ausbildung <small>Liste aller Ausbildungen</small></h2>
</div>
<div class="table-responsive">
    <table class="table table-bordered">
        <tr>
            <th>Name</th>
            <th>Kategorie</th>
            <th>Voraussetzungen</th>
        </tr>
        {% for training in training_list %}
        <tr>
            <td>{{ training.name }}</td>
            <td>{{ training.category.name }}</td>
            <td>
                {% for prerequisite in training.prerequisites.all %}
                    {{ prerequisite.name }}<br>
                {% endfor %}
            </td>
        </tr>
        {% endfor %}
    </table>
</div>
{% endblock %}

Bergwacht-System/BergwachtSystem/trainings/templates/trainings/training_permit.html
{% extends 'training_base.html' %}

{% block title %} Ausbildungen {% endblock %}

{% block training_content %}
<div class="page-header">
    <h2>Ausbildung
        <small>Teilnehmer zu Ausbildung anmelden</small>
    </h2>
</div>

<div class="row">
    <div class="col-md-9">
        <div class="panel panel-default">
            <!-- Default panel contents -->
            <div class="panel-heading">
                <h2 class="panel-title">
                    Ausbildung Details
                </h2>
            </div>
            <table class="table">
                <tr>
                    <th>Ausbildung</th>
                    <td>{{ training_event.training.name }}</td>
                </tr>
                <tr>
                    <th>Ausbildungstyp</th>
                    <td>{{ training_event.training.category.name }}</td>
                </tr>
                <tr>
                    <th>Von</th>
                    <td>{{ training_event.event_start }}</td>
                </tr>
                <tr>
                    <th>Bis</th>
                    <td>{{ training_event.event_end }}</td>
                </tr>
                <tr>
                    <th>Teilnehmerzahl</th>
                    <td>
                        <div class="progress">
                            {% if training_event.getMemberCount <= training_event.max_member %}
                            <div class="progress-bar progress-bar progress-bar-success" role="progressbar"
                                 aria-valuenow="{{ training_event.getMemberCount }}*100%/{{ training_event.minaek }}"
                                 aria-valuemin="0"
                                 aria-valuemax="100"
                                 style="min-width: 2em; width: calc({{ training_event.getMemberCount }}*100%/{{ training_event.max_member }});">
                                {{ training_event.getMemberCount }}/{{ training_event.max_member }}
                            </div>
                            {% else %}
                            <div class="progress-bar progress-bar-danger" role="progressbar"
                                 aria-valuenow="100%" aria-valuemin="0"
                                 aria-valuemax="100"
                                 style="min-width: 2em; width: 100%">
                                {{ training_event.getMemberCount }}/{{ training_event.max_member }}
                            </div>
                            {% endif %}
                        </div>
                    </td>
                </tr>
                <tr>
                    <th>Voraussetzungen</th>
                    <td>{% for prerequisite in training_event.training.prerequisites.all %}
                        {{ prerequisite.name }}<br>
                        {% endfor %}
                    </td>
                </tr>
                <tr>
                    <th>Ausbilder</th>
                    <td>
                        {% for trainer in training_event.trainer.all %}
                        <a href="{% url 'member_administration:member_detail' trainer.user.username %}">
                            {{ trainer.user.first_name}} {{ trainer.user.last_name }}</a>
                        <br>
                        {% endfor %}
                    </td>
                </tr>
            </table>
        </div>
    </div>
    <div class="col-md-3">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Aktionen</h3>
            </div>
            <div class="btn-group-vertical btn-block" role="group">
                <a href="mailto: {% for member in training_event.participants.all %}{{ member.user.email }}, {% endfor %}"
                   class="btn btn-success">Mail an alle Teilnehmer</a>
                <a href="{% url 'trainings:accept_member_trainings' training_event.training_event_id %}"
                   class="btn btn-default">Teilnahme eintragen</a>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-6">
        <div class="panel panel-default">
            <!-- Default panel contents -->
            <div class="panel-heading">
                <h2 class="panel-title">
                    Teilnehmer, die Zeit haben
                </h2>
            </div>
            <table class="table">
                {% for takes_part in possible_participants %}
                <tr>
                    <td><a href="{% url 'member_administration:member_detail' takes_part.member.user.username %}">
                        {{ takes_part.member.user.last_name }}, {{ takes_part.member.user.first_name }}</a>
                        <br>
                        <small>
                            {% for pre in training_event.training.prerequisites.all %}
                            {% if pre in takes_part.member.trainings.all %}
                            <span class="glyphicon glyphicon-ok" aria-hidden="true"></span> {{pre.name}} <br>
                            {% else %}
                            <span class="glyphicon glyphicon-remove" aria-hidden="true"></span> {{pre.name}} <br>
                            {% endif %}
                            {% endfor %}
                            Anmeldung: {{ takes_part.first_register_timestamp | date:'d.m.Y'}} -
                            {{ takes_part.first_register_timestamp | date:'H:i'}}
                        </small>
                    </td>
                    <td>
                        <a href="{% url 'trainings:register_for_training' training_event.training_event_id takes_part.member.user.username %}"
                           class="btn btn-primary btn-sm"><span class="glyphicon glyphicon-ok"
                                                                aria-hidden="true"></span></a>
                        <a href="{% url 'trainings:deregister_user_time_for_training' training_event.training_event_id takes_part.member.user.username %}"
                           class="btn btn-danger btn-sm"><span class="glyphicon glyphicon-remove"
                                                               aria-hidden="true"></span></a>
                    </td>
                </tr>
                {% endfor %}
            </table>
        </div>
    </div>
    <div class="col-md-6">
        <div class="panel panel-default">
            <!-- Default panel contents -->
            <div class="panel-heading">
                <h2 class="panel-title">
                    Angemeldete Teilnehmer
                </h2>
            </div>
            <table class="table">
                {% for member in training_event.participants.all %}
                <tr>
                    <td><a href="{% url 'member_administration:member_detail' member.user.username %}">
                        {{ member.user.last_name }}, {{ member.user.first_name }}</a>
                    </td>
                    <td>
                        <a href="{% url 'trainings:deregister_for_training' training_event.training_event_id member.user.username %}"
                           class="btn btn-danger btn-xs"><span class="glyphicon glyphicon-remove"
                                                               aria-hidden="true"></span></a>
                    </td>
                </tr>
                {% endfor %}
            </table>
        </div>
    </div>
</div>
{% endblock %}

Bergwacht-System/BergwachtSystem/trainings/templates/trainings/training_start.html
{% extends 'training_base.html' %}

{% block title %} Ausbildungen {% endblock %}

{% block training_content %}
<div class="page-header">
<h2>Ausbildung <small>Start</small></h2>
</div>
{% endblock %}